// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_As54N9jM_Bda15vGCrK-tCWoYrQ5Dy4',
    appId: '1:823688142351:web:7ec40a29a63f1cc9e4cd7a',
    messagingSenderId: '823688142351',
    projectId: 'hikersafrique-b611d',
    authDomain: 'hikersafrique-b611d.firebaseapp.com',
    databaseURL:
        'https://hikersafrique-b611d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hikersafrique-b611d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwxQdBjH-fMhgMJgcf0bVaYsZxcguYrc',
    appId: '1:823688142351:android:caa22046b6e8cf7fe4cd7a',
    messagingSenderId: '823688142351',
    projectId: 'hikersafrique-b611d',
    databaseURL:
        'https://hikersafrique-b611d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hikersafrique-b611d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9AzvDVRD-17p1P4Pv6-pA72UHkrjxnBQ',
    appId: '1:823688142351:ios:0e877b8d5bb26dd7e4cd7a',
    messagingSenderId: '823688142351',
    projectId: 'hikersafrique-b611d',
    databaseURL:
        'https://hikersafrique-b611d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hikersafrique-b611d.appspot.com',
    iosClientId:
        '823688142351-ct6pvjqd4ct8svcg68ug13f9571rk51g.apps.googleusercontent.com',
    iosBundleId: 'com.hikersafrique.bless.hikersafrique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9AzvDVRD-17p1P4Pv6-pA72UHkrjxnBQ',
    appId: '1:823688142351:ios:0e877b8d5bb26dd7e4cd7a',
    messagingSenderId: '823688142351',
    projectId: 'hikersafrique-b611d',
    databaseURL:
        'https://hikersafrique-b611d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hikersafrique-b611d.appspot.com',
    iosClientId:
        '823688142351-ct6pvjqd4ct8svcg68ug13f9571rk51g.apps.googleusercontent.com',
    iosBundleId: 'com.hikersafrique.bless.hikersafrique',
  );
}
